"""create wallets table

Revision ID: e649fde87117
Revises: 
Create Date: 2026-03-27 19:10:47.145172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e649fde87117'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('wallet_uuid', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_wallets_balance_non_negative'),
    sa.PrimaryKeyConstraint('wallet_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
